### ISSUE TITLE
Error view

### ISSUE THREAD

**Issue by Karyum** [foundersandcoders/nazareth-events#110]
Currently when an error occurs in the app, the title will change to "Not found" and the page would be empty and thats eat.

But thats not helpful on mobile much so render an actual error page when an error occurs.

but not sure what the content of the error page would be @finnhodgkin  ? 

- [x] setup error view #116 
- [x] render the view in error handling #123

**Comment by finnhodgkin** [comment]
For now I think just displaying the normal app header with a relevant error message instead of the events. Something like 'No events found'.
