### ISSUE TITLE
Deployment costs

### ISSUE THREAD

**Issue by Karyum** [foundersandcoders/nazareth-events#134]
Nazareth events is at stage where we need someone's visa for deployment costs :sweat_smile: , there is 3 stuff that we need : 
1) a visa to signup for AWS S3 image hosting. signing up for AWS is free the first 12 months after that it's going to be "pay-as-you-go" method of paying where for 1 gb it's 0.024$.

2) "Hobby" Heroku is for ability to change the doman name of the website and it also never sleeps.

3) A domain for the app which costs 4 shekels for 1 year on godaddy.com.

ps: maybe we should also consider buying the "Hobby" addon on Heroku for the OTP api ? since it's connected directly with Nazareth Events.

**Comment by sofer** [comment]
@Karyum Tareq has agreed at our most recent meeting with NCTA to discuss this with you. There is no reason why spending should not be approved. I recommend not giving him a choice, but just go with the option that you think makes most sense. I agree with your recommendation about paying to upgrade to a hobby dyno for the platform, too.
