### ISSUE TITLE
Reskin for the app

### ISSUE THREAD

**Issue by Karyum** [foundersandcoders/nazareth-events#141]
The app needs a bit of cleanup and a new design.

@finnhodgkin is working on it and going to provide wireframes!

**Comment by finnhodgkin** [comment]
### Home screen
![home](https://user-images.githubusercontent.com/22300773/33836266-99e1468a-de91-11e7-94a2-b684783b6db9.png)
-----
### Search open
![search](https://user-images.githubusercontent.com/22300773/33836273-9e98c018-de91-11e7-9d7a-8f2f1aaa5be8.png)
-----
### Search and filters open
![searchwithfilters](https://user-images.githubusercontent.com/22300773/33836275-a0ae88ec-de91-11e7-85ce-8da26a515a7c.png)
-----
### Calendar open

My print screen has decided to tint everything... Just imagine the background color for the calendar is white and that it has a 0.3rem grey bottom border. 
![calendar](https://user-images.githubusercontent.com/22300773/33836281-a3e17ca4-de91-11e7-8c12-87fd09c5ce97.png)

**Comment by finnhodgkin** [comment]
![eventscrolled](https://user-images.githubusercontent.com/22300773/33841102-67d63674-de9f-11e7-9c1b-9d8e5a3951a5.png)
![event](https://user-images.githubusercontent.com/22300773/33841104-6a74cc6a-de9f-11e7-9962-fc758ff21ba5.png)
