### ISSUE TITLE
Calendar UI/UX enhacements

### ISSUE THREAD

**Issue by Karyum** [foundersandcoders/nazareth-events#142]
As a user 
I would like the calendar to be more clear and informative (current date, selected date)
so i don't get lost in the app and the filter system

# Acceptance criteria

- [x] Display current date on the calendar - #141 
- [x] Display date selection  
- [x] (Bug) query string is really long in the url for date filters - #

**Comment by finnhodgkin** [comment]
Something like this but with a white background and small dots underneath the dates for events (currently shown via underline): 

![calendar](https://user-images.githubusercontent.com/22300773/33840975-1955a6e2-de9f-11e7-850f-ebbcbf19d574.png)

**Comment by Karyum** [comment]
@finnhodgkin looks great to me :+1:
