### ISSUE TITLE
Make sure data entry platform is up and running

### ISSUE THREAD

**Issue by des-des** [foundersandcoders/nazareth-events#146]
This needs a companion issue in data entry repo. @Karyum will create once he has investigates

**Comment by Karyum** [comment]
the data entry is working fine locally, so it must be something from heroku not sure what, probably ahsn't been deployed after the api url change

**Comment by Karyum** [comment]
so the problem was that the app wasnt deployed after the [change api url pull request](https://github.com/foundersandcoders/OTP-Data-Entry/pull/85) was merged, so i reached out for previous developers of the data entry and got hold of the account and deployed it. 

T: 30min

**Comment by des-des** [comment]
:sparkles:
