### ISSUE TITLE
Event details crashes when no address provided

### ISSUE THREAD

**Issue by Karyum** [foundersandcoders/nazareth-events#158]
I guess first as an action point we have to make all forms to have a required address input.

but we also should handle for when there is no address available in the event/place 
so i was thinking it would default to the Nazareth culture and tourism association ( Khan al Basha ) 
what do you think @finnhodgkin

**Comment by finnhodgkin** [comment]
I reckon just default to Nazareth as a whole: 'Nazareth, Israel'?

**Comment by Karyum** [comment]
@finnhodgkin yeah that is also an option and we could give a message of like `Address was not specified` or something like that. thoughts?

but the reason i chose the NCTA is cause they know every place in Nazareth and events, but now thinking about it if the event is in the evening and they would come to the NCTA they would find it closed and they would be stuck :stuck_out_tongue_winking_eye:

**Comment by finnhodgkin** [comment]
Yeah I think having the NCTA number when no phone number is supplied would be more appropriate. Don't want people to arrive at the NCTA thinking it's the event location.

**Comment by Karyum** [comment]
- [ ] show a message to the user when no location has been found.
- [ ] If a phone number for the place is not provided, show the phone number of the NCTA
