### ISSUE TITLE
Host on nazarethtoday domain

### ISSUE THREAD

**Issue by des-des** [foundersandcoders/nazareth-events#165]

**Comment by des-des** [comment]
@Karyum still nothing: http://www.nazarethtoday.com/

**Comment by Karyum** [comment]
So currently is redirecting to heroku so i think it's just a matter of us changing settings in heroku, i suspect it's the ssl but still not sure

**Comment by Karyum** [comment]
I have contacted the "domain guy" again, and he said his going to check in the OTP's heroku account and call me back ( but again that never happend ).
so my next step is contacting Tareq asking for help to speed this process up, cause if anyone has the knowledge to change the domain it would be the "domain guy", and not really us. and if theres anyone who can be more annoying than me that would be Tareq

**Comment by Karyum** [comment]
http://www.nazarethtoday.com/

# It's Done!! :tada:
