### ISSUE TITLE
CSS not compatible with every browser

### ISSUE THREAD

**Issue by Karyum** [foundersandcoders/nazareth-events#177]
we should setup vendor prefixes to CSS cause the website looks weird on Firefox, the question is should we keep it in pure css ? and just add the vendor prefixes or restyle with Tachyons or anything else?

what do you think @des-des ?

**Comment by des-des** [comment]
@Karyum 

Have you seen this: https://github.com/des-des/tachyons-webpack-boilerplate/blob/master/webpack.config.js

This shows how to add postcss to webpack config. It users the same postcss plugins as tachyons. This means later down the line we can do magic with tachyons if we like

Ie transpile the css using this rule here: https://github.com/des-des/tachyons-webpack-boilerplate/blob/master/webpack.config.js#L31

This will give us auto-prefixer, among other things: https://github.com/tachyons-css/tachyons-build-css/blob/master/index.js#L16

**Comment by Karyum** [comment]
@des-des so first of i should refactor the css using Tachyons :smile: and then while im at it add the rule for css with Tachyons postcss ......
correct me if im wrong is it just cause this makes the css in our app scalable ?

**Comment by Karyum** [comment]
huh.. so now do i actually need Tachyons or should i just stay with pure CSS since postCSS-loader just adds browsers compatibility for me ?


[ *sorry this message was supposed to be sent 7 hours ago, but github didn't allow it :sweat_smile:* ]
