### ISSUE TITLE
clicking on the calendar would render that day onwards

### ISSUE THREAD

**Issue by shiryz** [foundersandcoders/nazareth-events#40]
Silke has responded to this issue: https://github.com/FACN1/nazareth-events/issues/104#issuecomment-329496713

> Hi Shireen.
Thank you for being patient with me.
My idea is, that when you choose one day in the calendar it will give you the events from this day and onwards.

**Comment by mattlub** [comment]
🎉 😛

**Comment by Karyum** [comment]
@shiryz it was never agreed on how much "onwards" it should  but apparently it was done when i was in the holiday without anyone agreeing on how much it should be
