### ISSUE TITLE
date formatting on the home page

### ISSUE THREAD

**Issue by mattlub** [foundersandcoders/nazareth-events#43]
Needs to be something like:

Some Event
Wednesday 27th September
09:00 - 12:00
At Liwan

![screen shot 2017-09-25 at 09 22 37](https://user-images.githubusercontent.com/16781318/30798961-2efa9286-a1d3-11e7-860b-f90f3a4e4ab4.png)

**Comment by JWLD** [comment]
Done @mattlub

**Comment by JWLD** [comment]
trudat, will crack the whip

**Comment by JWLD** [comment]
@Karyum could we add the place to the list of events?
