### ISSUE TITLE
Wireframes / UX Advice

### ISSUE THREAD

**Issue by JWLD** [foundersandcoders/nazareth-events#52]
**Wireframes**
1) Landing page / home view - header bar, list of events, 'no upcoming events' message
2) Calendar modal / dropdown
3) Specific event view
4) Add event form
5) Account dashboard when user logs in (stretch?)
6) Specific place view with list of all events for that place (stretch?)

****

**UX / User Journeys**
1) Anyone can view upcoming events on home page
2) Anyone can open a calendar and select a date to view nearby events
3) Anyone can click event on homepage to get more details
4) Host can log in to the OTP and add an event - how to add a place if it doesn't exist?
5) Host can view all their events on an account dashboard (stretch?)
6) Anyone can view a specific place to see all events being held there (stretch?)

**Comment by m4v15** [comment]
Current website : http://nazareth-events.herokuapp.com/
