### ISSUE TITLE
not all events are rendering

### ISSUE THREAD

**Issue by mattlub** [foundersandcoders/nazareth-events#59]
I can see in the network tab that the request is returning 5 events, but only one is rendering because of a script error:
![screenshot from 2017-10-01 18-16-20](https://user-images.githubusercontent.com/16781318/31057118-31ce0432-a6d5-11e7-8268-b3522691dd6a.png)

**Comment by Karyum** [comment]
@mattlub yeah but that one event that is rendering is the only one that has a place object or place id

**Comment by mattlub** [comment]
Ok cool, you can close this if it's not an issue?

**Comment by Karyum** [comment]
Yeah im not sure it's an issue since now we are posting events to the api with the place id, and the api takes that id and replaces it with an object.
It's probably the data entry team adding those events :stuck_out_tongue_winking_eye: :maple_leaf:
